theme: jekyll-theme-dinky
title: Foundations for Open Scholarship Strategy Development
description: TOC [Purpose of this Document](#Purpose)
[Strategy](#Strategy)
[Short-term strategy, >2 years](#Short)
[Mid-term strategy, 2-5 years](#Middle)
[Long-term strategy, 5+ years](#Long)
[What is Open Scholarship?](#What_is)
[State of the Movement](#State)
[Top Strategic Priorities for Open Scholarship](#Priorities)
[Democratization](#Democratization)
[Pragmatism and transparency](#Pragmatism)
[Infrastructure](#Infrastucture)
[Public good](#Public)
[Measurement](#Measurement)
[Community and inclusion](#Community)
[Movement Strengths](#Strengths)
[Movement Challenges](#Challenges)
[External conditions](#External)
[Internal conditions](#Internal)
[Opportunities](#Opportunities)
[Threats](#Threats)
